Repository microsoft/kafka-connect-cosmosdb, pull requests merged in 2020-12, with the labels that each got.

#173 Updated maven plugin dependencies to latest supporting java11
  pom.xml
Labels: bug

#184 Developer Docs
  DEVELOPER_WALKTHROUGH.MD
  README.md
Labels: gold

#187 Source Connector Docs
  doc/README_Source.md
  doc/images/delete-source-connector.png
Labels: gold

#197 Exposed upsert configuration for Sink Connector and added user-agent to cosmosdb java client
  src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/SettingDefaults.java
  src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/CosmosDBSinkTask.java
  src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/SinkSettingDefaults.java
  src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/SinkSettings.java
  src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/CosmosDBSourceTask.java
  src/test/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/CosmosDBSinkTaskTest.java
Labels: gold

#208 Add engineering checklist (#207)
  .github/ISSUE_TEMPLATE/EngineeringFundChecklist.md
Labels: internal
