Repository microsoft/kafka-connect-cosmosdb, pull requests merged in 2021-01, with the labels that each got.

#215 Renaming conf platform setup folders
  .github/workflows/mavenCI.yml
  .github/workflows/release.yml
  doc/Confluent_Platform_Setup.md
  doc/README_Sink.md
  doc/README_Source.md
  src/docker/.gitignore
  src/docker/configure-sink.ps1
  src/docker/configure-source.ps1
  src/docker/docker-compose.yml
  src/docker/java/com/microsoft/azure/cosmosdb/kafka/connect/IntegrationTest.java
  src/docker/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/PostToKafkaTest.java
  src/docker/resources/sink.config.json
  src/docker/resources/source.config.json
  src/docker/startup.ps1
  src/docker/startup.sh
Labels: blocked

#230 Added support for Arrays for Sink & Source Connectors
  pom.xml
  src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/CosmosDBSinkTask.java
  src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/sink/StructToJsonMap.java
  src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/CosmosDBSourceTask.java
  src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/JsonToStruct.java
  src/main/java/com/microsoft/azure/cosmosdb/kafka/connect/source/SourceSettings.java
Labels: demo

#234 Updated project readme to include supported data formats and converters
  README.md
  doc/images/converter-misconfigurations.png
Labels: gold

#257 fixing linter issues
  src/main/java/com/azure/cosmos/kafka/connect/sink/CosmosDBSinkTask.java
  src/main/java/com/azure/cosmos/kafka/connect/sink/CosmosDBWriteException.java
  src/main/java/com/azure/cosmos/kafka/connect/source/CosmosDBSourceTask.java
Labels: x-small (1)
